if(NOT DEFINED STITCH OR NOT DEFINED ASSETS OR NOT DEFINED OUT)
  message(FATAL_ERROR "Missing CLI test paths")
endif()
file(MAKE_DIRECTORY "${OUT}")
function(expect_failure name)
  file(REMOVE "${OUT}/${name}.png")
  execute_process(COMMAND "${STITCH}" ${ARGN} --output "${OUT}/${name}.png"
    RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 30)
  if(NOT result STREQUAL "2")
    message(FATAL_ERROR "${name}: expected exit code 2, got ${result}: ${stdout} ${stderr}")
  endif()
  if(EXISTS "${OUT}/${name}.png")
    message(FATAL_ERROR "${name}: invalid request wrote a panorama")
  endif()
endfunction()
expect_failure(unknown_mode --method invalid "${ASSETS}/synthetic/view0.png" "${ASSETS}/synthetic/view1.png")
expect_failure(bad_number --grid 32junk "${ASSETS}/synthetic/view0.png" "${ASSETS}/synthetic/view1.png")
expect_failure(missing_input "${ASSETS}/missing.png" "${ASSETS}/synthetic/view1.png")
expect_failure(blank --method rew "${ASSETS}/synthetic/blank.png" "${ASSETS}/synthetic/blank.png")
expect_failure(duplicate --method rew --method niswgsp "${ASSETS}/synthetic/view0.png" "${ASSETS}/synthetic/view1.png")
execute_process(COMMAND "${STITCH}" --method gesgsp --device auto --output "${OUT}/cli.png" --report "${OUT}/cli.json"
  "${ASSETS}/synthetic/view0.png" "${ASSETS}/synthetic/view1.png"
  RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 120)
if(NOT result STREQUAL "0" OR NOT EXISTS "${OUT}/cli.png")
  message(FATAL_ERROR "CLI end-to-end failed: ${result} ${stdout} ${stderr}")
endif()
file(READ "${OUT}/cli.json" report)
string(JSON method GET "${report}" method)
string(JSON device GET "${report}" actual_device)
if(NOT method STREQUAL "gesgsp" OR NOT device MATCHES "^(cpu|cuda)$")
  message(FATAL_ERROR "CLI report is invalid")
endif()
