file(READ "${ASSETS}/manifest.json" manifest)
string(JSON count LENGTH "${manifest}" files)
math(EXPR last "${count}-1")
foreach(index RANGE 0 ${last})
  string(JSON relative GET "${manifest}" files ${index} path)
  string(JSON expected GET "${manifest}" files ${index} sha256)
  if(relative MATCHES "\\.\\." OR IS_ABSOLUTE "${relative}")
    message(FATAL_ERROR "Unsafe asset path: ${relative}")
  endif()
  file(SHA256 "${ASSETS}/${relative}" actual)
  if(NOT actual STREQUAL expected)
    message(FATAL_ERROR "Asset checksum mismatch: ${relative}")
  endif()
endforeach()
message(STATUS "Verified ${count} committed assets")
